a: "https://www.railstutorial.org/"
a_help: "https://www.railstutorial.org/help"
a_book: "https://www.railstutorial.org/book"
a_contact: "https://www.railstutorial.org/contact"
b: "http://screencasts.railstutorial.org/"
c: "http://rubyonrails.org/"
