rails: "https://www.railstutorial.org/"
rails_help: "https://www.railstutorial.org/help"
rails_book: "https://www.railstutorial.org/book"
rails_contact: "https://www.railstutorial.org/contact"
screencasts: "http://screencasts.railstutorial.org/"
ruby: "http://rubyonrails.org/"
link_Michael: "http://www.michaelhartl.com/"
rails_new: "http://news.railstutorial.org/"
